name: mirai
description: Mirai is a Server-Driven UI (SDUI) library for Flutter. Mirai allows you to build beautiful cross-platform applications with JSON in real time.
version: 0.5.0
homepage: https://github.com/Securrency-OSS/mirai.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  json_annotation: ^4.8.1
  logger: ^1.4.0
  dio: ^5.2.0+1
  mirai_framework:
    path: ../mirai_framework

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
